exclude: "docs|node_modules|migrations|.git|.github|venv"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.3.1
    hooks:
      - id: commitizen
        stages:
          - manual

  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.1.3
  #   - hooks:
  #     - id: python-safety-dependencies-check

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v7.8.1
  #   hooks:
  #     - additional_dependencies:
  #         - eslint@latest
  #         - vue-eslint-parser@latest
  #         - eslint-plugin-vue@latest
  #         - eslint-plugin-jquery@latest
  #         - eslint-plugin-eslint-plugin@latest
  #         - prettier@latest
  #         - eslint-config-prettier@latest
  #         - eslint-plugin-prettier@latest
  #         - babel-eslint
  #       args:
  #         - -c=.eslintrc.js
  #         - --fix
  #       id: eslint
  #       name: vue-eslint
  #       types:
  #         - vue

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v7.8.1
  #   hooks:
  #     - additional_dependencies:
  #         - eslint@latest
  #         - vue-eslint-parser@latest
  #         - eslint-plugin-vue@latest
  #         - eslint-plugin-jquery@latest
  #         - eslint-plugin-eslint-plugin@latest
  #         - prettier@latest
  #         - eslint-config-prettier@latest
  #         - eslint-plugin-prettier@latest
  #         - babel-eslint
  #       args:
  #         - -c=.eslintrc.js
  #         - --fix
  #       id: eslint
  #       name: js-eslint
