# Generated by Django 3.2.5 on 2021-07-26 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0008_auto_20210722_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data_file', models.FileField(upload_to='uploads/pictures/')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='flights.flight')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
