# Generated by Django 3.2.5 on 2021-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20210726_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='data_file',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
