# Generated by Django 3.2.5 on 2021-08-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_alter_picture_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
