# Generated by Django 3.2.5 on 2021-07-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='IATA',
            field=models.CharField(default='AAA', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='ICAO',
            field=models.CharField(max_length=4),
        ),
    ]
