# Generated by Django 3.2.5 on 2021-07-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20210722_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='data_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
