# Generated by Django 3.2.5 on 2021-07-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_data_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['name']},
        ),
    ]
