# Generated by Django 3.2.5 on 2021-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='landing',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='takeoff',
            field=models.DateTimeField(null=True),
        ),
    ]
