# Generated by Django 3.2.5 on 2021-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20210722_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='data_file',
            field=models.FileField(upload_to='uploads/flights/'),
        ),
    ]
