# Generated by Django 3.2.5 on 2021-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20210722_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waypoint',
            options={'ordering': ['flight', 'index']},
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='alt',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
