# Generated by Django 3.2.5 on 2021-07-28 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_airport_onair_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='embed_id',
            field=models.CharField(default='000', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('owner', 'embed_id'), name='unique flight_owner'),
        ),
    ]
