# Generated by Django 3.2.5 on 2021-08-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_alter_flight_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
