# Generated by Django 3.2.5 on 2021-08-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_flight_intended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='IATA',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
