# Generated by Django 3.2.5 on 2021-08-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0016_alter_aircraft_onair_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['start']},
        ),
    ]
