# Generated by Django 3.2.5 on 2021-08-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_alter_flight_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-start']},
        ),
    ]
