# Generated by Django 3.2.5 on 2021-08-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='icons',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Icons'), (2, 'Circle')], default=1),
        ),
    ]
